### ISSUE TITLE
Does your blog have an RSS feed?

### ISSUE THREAD

**Issue by simevidas** [cssence/cssence.com#3]
I’d like to subscribe.

**Comment by cssence** [comment]
Great to hear. Not yet, but it will! Working on it, and 2024 will be the year. After all, I've written the following not too long ago:

> [T]hough sadly I’m not riding the RSS train (yet).
—https://cssence.com/2023/originally-published-elsewhere/

**Comment by cssence** [comment]
Done.

Links to all available feeds can be found under https://cssence.com/rss/

**Comment by cssence** [comment]
**Update June 2025:**

Now even the root folder contains an `rss.xml`, which is now the recommended way to subscribe;
see https://cssence.com/2025/whimsica11y-rssjoy/#comment-6 for more details.
